services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm run dev
    env_file:
      - ./client/.env.local
    depends_on:
      server:
        condition: service_healthy

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./server/.env
    healthcheck:
      test: CMD curl -f http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


 