import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/context/ThemeContext";
import { AuthUserProvider } from "@/context/AuthUserContext";
import AppShellAuth from "@/components/AppShellAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Job Scraper",
  description: "Job scraping application",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <AuthUserProvider>
            <AppShellAuth>{children}</AppShellAuth>
          </AuthUserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
// import { type Metadata } from 'next'
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from '@clerk/nextjs'
// import { Geist, Geist_Mono } from 'next/font/google'
// import './globals.css'

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// })

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// })

// export const metadata: Metadata = {
//   title: 'Clerk Next.js Quickstart',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton>
//                 <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
//                   Sign Up
//                 </button>
//               </SignUpButton>
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   )
// }
// import "./globals.css"; // Make sure this import is here
// import { Inter } from "next/font/google";
// import { ThemeProvider } from "@/context/ThemeContext";
// import { AuthUserProvider } from "@/context/AuthUserContext";
// // import Navbar from "@/components/navbar/Navbar";
// import AppShellAuth from "@/components/AppShellAuth";
// import type { AuthUser } from "@/types/index";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Job Scraper",
//   description: "Job scraping application",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ThemeProvider>
//           <AuthUserProvider>
//             <AppShellAuth>{children}</AppShellAuth>
//           </AuthUserProvider>
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }
